### ISSUE TITLE
Issue with titles in nixpkgs manual indexation

### ISSUE THREAD

**Issue by samueldr** [grahamc/docbook-index#1]
These might be two different issues, or come from the same root cause, haven't investigated.

## Titles truncated at the first tag encountered

`10.14.2.1.1. Missing tkinter module standard library` has its title indexed as `Mising`.

## Titles for functions are paren't title

`8.1.2.26. lib.attrsets.recursiveUpdate` has its title indexed as `Attribute-Set Functions`

* * *

Without looking at the implementation, the second part feels like it's a common issue with the first part; only that the whole title is wrapped in a tag, meaning that it would be an empty title, which I would assume falls back on the parent title.

**Comment by grahamc** [comment]
This one is actually two separate issues: function names are not `<title>`s, they're `<term>`s. The first one is because we "forget" to capture `<title>`'s sub-element text. You can split them up if you'd like, or not, up to you :) Thank you for these two!

**Comment by grahamc** [comment]
This issue will make for good airplane work, and also pushes the currenty extremely simplistic code in to needing a proper state machine and tests. Thank you :)

**Comment by grahamc** [comment]
This was, btw, the same issue :) I was confusing the function's XML with the nix.conf XML.
